features/java/src/test/java/gradle/cucumber/Collectiondefs.java
Before the method `validateSpecifications` didn't take an index an a collection in parameters and could be used for any collection.  
This PR change the signature to match the rest of the collection controller. The method now take an index and a collection in addition to the specifications for this collection.
I also modify the `updateSpecifications` method. The method was taking an index and collection in parameter but it didn't scope the specifications to the collection. 
Related PR: https://github.com/kuzzleio/sdk-javascript/pull/318, https://github.com/kuzzleio/sdk-go/pull/211, https://github.com/kuzzleio/sdk-c/pull/13, https://github.com/kuzzleio/sdk-cpp/pull/11, https://github.com/kuzzleio/sdk-java/pull/13, https://github.com/kuzzleio/documentation-V2/pull/51
- Step 1: Run Kuzzle …
=> KZL - 547 - Update validate specification signature

swig/common.i
In result structure like `subscribe_result` we have a `int status` used when Kuzzle respond with an error to throw the corresponding exception in CPP. As `error` and `stack`, we don't want these attributes to be wrapped with SWIG so we have an `%ignore` rule.  
But exceptions also have a `status` attribute and in this case we want it to be wrapped.
This PR ignore `status` only in result structure.
- Step 1 : Generate the SDK: `docker run --rm -it --network ci_default --link kuzzle -v "$(pwd)":/mnt kuzzleio/sdk-cross:gcc make clean all`
- Step 2 : Check method presence: `javap -classpath build/kuzzlesdk-1.0.0-amd64.jar  io.kuzzle.sdk.KuzzleException | grep getStatus`
=> Don't ignore status attribut for Exceptions

.github/pull_request_template.md, swig/common.i, swig/core.i, swig/kcore.i, swig/typemap.i
This pr allow usage of `Options`, `QueryOptions` and `RoomOptions` with default values
https://github.com/kuzzleio/sdk-cpp/pull/21 :arrow_left: :large_blue_circle:
Save the following snippet as `Test.java` at the sdk root
```
public class Test {
Options options = new Options();
System.out.println(options.getQueueTTL());
RoomOptions roomOptions = new RoomOptions();
System.out.println(roomOptions.getScope());
}
}
```
Compile and execute this file with: `javac -cp ".:./build/kuzzlesdk-1.0.0-amd64.jar" Test.java && java -cp ".:./build/kuzzlesdk-1.0.0-amd64.jar" Test`
=> Fix wrapping of options and room options

features/java/src/test/java/gradle/cucumber/Documentdefs.java
This PR adds some minimal functional tests for `document`.`search` and `next`.
=> Kzl 642 functional tests

swig/common.i, swig/typemap.i
Update SWIG templates:
* move the `queue_ttl` rename to its belonging section
* remove the duplicate `auto_replay` rename
* remove the obsolete `offline_mode` rename
* remove the obsolete `char**` typemaps: 
1. these typemaps  consider these char arrays to be NULL-terminated, but they are not: the CGo SDK uses length-defined arrays instead
2. there are no such types left in the C++ SDK anyway, they are all wrapped in C++ containers, to make SWIG wrapping easier
=> Remove obsolete renames and typemaps

.travis.yml, src/main/java/io/kuzzle/sdk/API/Controllers/AuthController.java, src/main/java/io/kuzzle/sdk/CoreClasses/Task.java, src/main/java/io/kuzzle/sdk/Kuzzle.java, src/test/java/io/kuzzle/test/API/Controllers/AuthControllerTest.java, src/test/java/io/kuzzle/test/CoreClasses/TaskTest/TaskTests.java, src/test/java/io/kuzzle/test/CoreClasses/TaskTest/TestableTask.java, src/test/java/io/kuzzle/test/KuzzleTests.java, src/test/java/io/kuzzle/test/ProtocolTest/WebSocketTests.java
- Add unit test for `AuthController`
- Fix an issue in the `Task` class where not every `Future` would be resolved when running in multi Thread.
```sh
./gradlew test
```
- Run unit tests on Travis
=> Auth controller tests + Fix Task

.ci/doc/templates/default.tpl.java, .travis.yml, doc/3/controllers/realtime/index.md, doc/3/controllers/realtime/subscribe/index.md, doc/3/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.java, doc/3/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.test.yml, doc/3/controllers/realtime/subscribe/snippets/document-notifications.java, doc/3/controllers/realtime/subscribe/snippets/document-notifications.test.yml, doc/3/core-classes/subscribe-options/index.md, doc/3/essentials/realtime-notifications/index.md, src/main/java/io/kuzzle/sdk/API/Controllers/RealtimeController.java, src/main/java/io/kuzzle/sdk/CoreClasses/Responses/Response.java, src/main/java/io/kuzzle/sdk/Handlers/NotificationHandler.java, src/main/java/io/kuzzle/sdk/Kuzzle.java, src/main/java/io/kuzzle/sdk/Options/SubscribeOptions.java, src/test/java/io/kuzzle/test/API/Controllers/RealtimeControllerTest.java
Add a `RealtimeController` with the `subscribe` method.
```sh
./gradlew test
```
=> RealtimeController:subscribe

.travis.yml, doc/3/controllers/index/create/index.md, doc/3/controllers/index/create/snippets/create.java, doc/3/controllers/index/create/snippets/create.test.yml, doc/3/controllers/index/delete/index.md, doc/3/controllers/index/delete/snippets/delete.java, doc/3/controllers/index/delete/snippets/delete.test.yml, doc/3/controllers/index/exists/index.md, doc/3/controllers/index/exists/snippets/exists.java, doc/3/controllers/index/exists/snippets/exists.test.yml, doc/3/controllers/index/index.md, doc/3/controllers/index/list/index.md, doc/3/controllers/index/list/snippets/list.java, doc/3/controllers/index/list/snippets/list.test.yml, doc/3/controllers/index/m-delete/index.md, doc/3/controllers/index/m-delete/snippets/mDelete.java, doc/3/controllers/index/m-delete/snippets/mDelete.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/IndexController.java, src/main/java/io/kuzzle/sdk/Exceptions/KuzzleExceptionCode.java, src/main/java/io/kuzzle/sdk/Kuzzle.java, src/test/java/io/kuzzle/test/API/Controllers/IndexControllerTest.java
Add Index Controller.
```sh
./gradlew test
```
- Run documentation's tests snippet in travis
- Fix a typo in enum `KuzzleExceptionCode.MISSING_QUERY`
=> Add Index controller

.ci/doc/templates/print-result-array.tpl.java, doc/3/controllers/document/m-get/index.md, doc/3/controllers/document/m-get/snippets/m-get.java, doc/3/controllers/document/m-get/snippets/m-get.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/DocumentController.java, src/main/java/io/kuzzle/sdk/Kuzzle.java, src/test/java/io/kuzzle/test/API/Controllers/DocumentTest/DocumentTest.java
This PR implements the `mGet` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data` and a `yellow-taxi` collection in the admin console. Create 2 documents with id `some-id1` and `some-id2`.
```java
public class mGetDocument { …
```
=> Add document:mGet

doc/3/controllers/document/delete/index.md, doc/3/controllers/document/delete/snippets/delete.java, doc/3/controllers/document/delete/snippets/delete.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/DocumentController.java, src/main/java/io/kuzzle/sdk/Kuzzle.java, src/test/java/io/kuzzle/test/API/Controllers/DocumentTest/DocumentTest.java
This PR implements the `document:delete` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data` and a `yellow-taxi` collection in the admin console. Create a document with id `some-id`
```java
public class deleteDocument { …
```
=> Add document:delete

doc/3/controllers/document/replace/index.md, doc/3/controllers/document/replace/snippets/replace.java, doc/3/controllers/document/replace/snippets/replace.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/DocumentController.java, src/main/java/io/kuzzle/sdk/Kuzzle.java, src/test/java/io/kuzzle/test/API/Controllers/DocumentTest/DocumentTest.java
This PR implements the `document:replace` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data` and a `yellow-taxi` collection in the admin console. Create a document with id `some-id`
```java
public class replaceDocument { …
```
=> Add document:replace

doc/3/controllers/document/get/index.md, doc/3/controllers/document/get/snippets/get.java, doc/3/controllers/document/get/snippets/get.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/DocumentController.java, src/main/java/io/kuzzle/sdk/Kuzzle.java, src/test/java/io/kuzzle/test/API/Controllers/DocumentTest/DocumentTest.java
This PR implements the `document:get` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data` and a `yellow-taxi` collection in the admin console. Create a document with id `"some-id"`
```java
public class getDocument { …
```
=> Add document:get

.ci/doc/templates/print-result.tpl.java, doc/3/core-classes/kuzzle-options/index.md, doc/3/essentials/network-loss-resilience/index.md, doc/3/protocols/websocket-options/index.md, src/main/java/io/kuzzle/sdk/API/Controllers/RealtimeController.java, src/main/java/io/kuzzle/sdk/Kuzzle.java, src/main/java/io/kuzzle/sdk/Options/KuzzleOptions.java, src/main/java/io/kuzzle/sdk/Options/Protocol/WebSocketOptions.java, src/main/java/io/kuzzle/sdk/Protocol/ProtocolState.java, src/main/java/io/kuzzle/sdk/Protocol/WebSocket.java, src/test/java/io/kuzzle/test/API/Controllers/RealtimeControllerTest.java
depends on #67 
Add a auto reconnect / subscribe mechanism
=> Auto reconnect/resubscribe

doc/3/controllers/document/count/index.md, doc/3/controllers/document/count/snippets/count.java, doc/3/controllers/document/count/snippets/count.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/DocumentController.java, src/test/java/io/kuzzle/test/API/Controllers/DocumentTest/DocumentTest.java
This PR implements the `count` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data` and a `yellow-taxi` collection in the admin console. Create 5 documents with 3 of them containing a field `{"key":"value"}`.
```java
public class countDocument { …
```
=> Add document:count

doc/3/controllers/document/validate/index.md, doc/3/controllers/document/validate/snippets/validate.java, doc/3/controllers/document/validate/snippets/validate.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/DocumentController.java, src/test/java/io/kuzzle/test/API/Controllers/DocumentTest/DocumentTest.java
This PR implements the `validate` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data` and a `yellow-taxi` collection in the admin console.
```java
public class validateDocument {
try { …
```
=> Add document:validate

doc/3/controllers/collection/exists/index.md, doc/3/controllers/collection/exists/snippets/exists.java, doc/3/controllers/collection/exists/snippets/exists.test.yml, doc/3/controllers/collection/index.md, src/main/java/io/kuzzle/sdk/API/Controllers/CollectionController.java, src/main/java/io/kuzzle/sdk/Kuzzle.java, src/test/java/io/kuzzle/test/API/Controllers/CollectionTest.java
This PR implements the `collection:exists` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data` and a `yellow-taxi` collection.
```java
public class existsCollection {
try {
WebSocket ws = …
```
=> Add Collection controller and collection:exists

doc/3/controllers/collection/get-mapping/index.md, doc/3/controllers/collection/get-mapping/snippets/get-mapping.java, doc/3/controllers/collection/get-mapping/snippets/get-mapping.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/CollectionController.java, src/test/java/io/kuzzle/test/API/Controllers/CollectionTest.java
This PR implements the `collection:create` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data`, a collection `yellow-taxi`.
```java
public class getMappingCollection {
try {
WebSocket ws = …
```
=> Add collection:getMapping

doc/3/controllers/collection/create/index.md, doc/3/controllers/collection/create/snippets/create.java, doc/3/controllers/collection/create/snippets/create.test.yml, doc/3/controllers/document/m-update/snippets/m-update.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/CollectionController.java, src/test/java/io/kuzzle/test/API/Controllers/CollectionTest.java
This PR implements the `collection:create` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data`.
```java
public class createCollection {
try {
WebSocket ws = new WebSocket("localhost", opts); …
```
=> Add collection:create

doc/3/controllers/collection/truncate/index.md, doc/3/controllers/collection/truncate/snippets/truncate.java, doc/3/controllers/collection/truncate/snippets/truncate.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/CollectionController.java, src/test/java/io/kuzzle/test/API/Controllers/CollectionTest.java
This PR implements the `collection:truncate` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data`, a `yellow-taxi` collection with several documents in it.
```java
public class truncateCollection { …
```
=> Add collection:truncate

.ci/doc/templates/print-result-arraylist.tpl.java, doc/3/controllers/document/delete-by-query/index.md, doc/3/controllers/document/delete-by-query/snippets/delete-by-query.java, doc/3/controllers/document/delete-by-query/snippets/delete-by-query.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/DocumentController.java, src/test/java/io/kuzzle/test/API/Controllers/DocumentTest/DocumentTest.java
This PR implements the `deleteByQuery` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data` and a `yellow-taxi` collection in the admin console. Create 5 documents with 3 containing field `{"key":"value"}`.
```java
public class deleteByQueryDocument {
WebSocketOptions opts = new …
```
=> Add document:deleteByQuery

doc/3/controllers/document/update-by-query/index.md, doc/3/controllers/document/update-by-query/snippets/update-by-query.java, doc/3/controllers/document/update-by-query/snippets/update-by-query.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/DocumentController.java, src/test/java/io/kuzzle/test/API/Controllers/DocumentTest/DocumentTest.java
This PR implements the `updateByQuery` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data` and a `yellow-taxi` collection in the admin console. Create 5 documents with 3 containing field `{"key":"value"}`.
```java
public class updateByQueryDocument {
WebSocketOptions opts = new …
```
=> Add document:updateByQuery

.ci/doc/config.yml, doc/3/controllers/collection/get-specifications/index.md, doc/3/controllers/collection/get-specifications/snippets/get-specifications.java, doc/3/controllers/collection/get-specifications/snippets/get-specifications.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/CollectionController.java, src/test/java/io/kuzzle/test/API/Controllers/CollectionTest.java
This PR implements the `collection:getSpecifications` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data`, a `yellow-taxi` collection
```java
public class getSpecificationsCollection {
try { …
```
=> Add collection:getSpecifications

doc/3/controllers/collection/delete-specifications/index.md, doc/3/controllers/collection/delete-specifications/snippets/delete-specifications.java, doc/3/controllers/collection/delete-specifications/snippets/delete-specifications.test.yml, src/main/java/io/kuzzle/sdk/API/Controllers/CollectionController.java, src/test/java/io/kuzzle/test/API/Controllers/CollectionTest.java
This PR implements the `collection:deleteSpecifications` method with its unit tests.
Then, run Kuzzle, create an index `nyc-open-data`, a `yellow-taxi` collection
```java
public class deleteSpecificationsCollection { …
```
=> Add collection:deleteSpecifications

doc/3/controllers/collection/get-mapping/index.md, doc/3/controllers/collection/truncate/index.md, doc/3/controllers/document/delete-by-query/index.md, doc/3/controllers/document/update-by-query/index.md, doc/3/controllers/document/update/snippets/update.test.yml
Updated a few doc files to aim the real existing **.java** files, instead of some **.js**
- collection/**get-mapping**
- collection/**truncate**
- document/**delete-by-query**
- document/**update-by-query**
Clone and launch:
`npm install & npm run doc-prepare & npm run doc-build`
You should not see any errors related to missing snippets.
To get the ci build to succed, had to update [document/update test file](https://github.com/kuzzleio/sdk-java/blob/ad15a06170fa0d69f97b50a34a29705d40510617/doc/3/controllers/document/update/snippets/update.test.yml#L11) to expect:
`'expected: "_id=some-id, _version=2"'`
instead of:
`'{expected: "_id=some-id, _version=2"}'`
=> [fix] Correctly aim at the right doc snippet files

src/main/java/io/kuzzle/sdk/Kuzzle.java
- There was an issue where CompletableFutures were not completed  exceptionally when there was a TokenExpired error response, causing java applications using the SDK to be locked when  doing `.get()`  or `.join()` on the resulting Task of a controller action,
because the Future was never resolved.
=> Fix token expired

.travis.yml, doc/3/controllers/auth/update-self/snippets/update-self.test.yml, doc/3/getting-started/install/index.md, doc/3/migration/how-to/index.md, doc/3/migration/index.md, doc/frontmatter-errors.json
Add a "How to Migrate from SDK Java to SDK JVM" page
https://github.com/kuzzleio/sdk-java/issues/97
Since this doc use an example with `document:search`, https://github.com/kuzzleio/sdk-jvm/pull/23 has to be merged before
(the signature has been updated)
Typo in Getting Started
=> Add a "How to Migrate from SDK Java to SDK JVM" page
